import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { FileDown } from 'lucide-react'
import { api } from '../api/client'
type Case = {id: string; inspection_code: string; product_name: string|null; status: string; images_count: number}
export default function Reports() {
 const [items,setItems]=useState<Case[]>([]),[query,setQuery]=useState(''),[page,setPage]=useState(1),[total,setTotal]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState('')
 useEffect(()=>{const controller=new AbortController();api.get('/inspections',{params:{q:query,page,page_size:20},signal:controller.signal}).then(({data})=>{setItems(data.items);setTotal(data.total);setError('')}).catch(()=>{if(!controller.signal.aborted)setError('Could not load reports.')});return()=>controller.abort()},[query,page])
 async function download(item: Case,format: 'pdf'|'csv'|'json') {setBusy(item.id);setError('');try{const {data}=await api.get(`/inspections/${item.id}/reports/${format}`,{responseType:'blob',timeout:60000});const url=URL.createObjectURL(data);const link=document.createElement('a');link.href=url;link.download=`${item.inspection_code}.${format}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{setError('Could not generate the report. Please try again.')}finally{setBusy('')}}
 return <main className="p-6 max-w-6xl mx-auto"><div className="eyebrow">CASE EXPORTS</div><h1 className="text-3xl font-serif my-3">Reports</h1><p>Download inspection findings and evidence records.</p><label className="block my-5">Find a case<input className="block border rounded p-2 w-full" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Case number, product or manufacturer"/></label>{error&&<p role="alert">{error}</p>}
 <div className="space-y-3">{items.map(item=><article className="panel flex flex-wrap gap-4 justify-between" key={item.id}><div><Link className="font-semibold underline" to={`/inspections/${item.id}`}>{item.inspection_code}</Link><p>{item.product_name||'Untitled package'} · {item.images_count} photos</p><small>{item.status}</small></div><div className="flex gap-2 items-center">{(['pdf','csv','json'] as const).map(format=><button className="w-auto flex gap-2 items-center px-3 py-2" key={format} disabled={!!busy} onClick={()=>download(item,format)}><FileDown size={16}/>{format.toUpperCase()}</button>)}</div></article>)}</div>{!items.length&&!error&&<p className="my-6">No matching cases.</p>}<div className="flex justify-between my-5"><button className="w-auto" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} · {total} cases</span><button className="w-auto" disabled={page*20>=total} onClick={()=>setPage(p=>p+1)}>Next</button></div></main>
}
