"""Phase 7 context facts and immutable rule-input snapshots."""
from alembic import op
import sqlalchemy as sa
revision = "0006_context"
down_revision = "0005_extraction"
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_resolution_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inspector_input', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'PARTIAL', 'FAILED', name='context_run_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('facts_created', sa.Integer(), nullable=False),
    sa.Column('conflicts_detected', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id', 'version', 'input_fingerprint', name='uq_context_input')
    )
    op.create_index(op.f('ix_context_resolution_runs_inspection_id'), 'context_resolution_runs', ['inspection_id'], unique=False)
    op.create_table('context_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('fact_type', sa.Enum('PRODUCT_CATEGORY', 'PACKAGE_TYPE', 'IMPORT_STATUS', 'COUNTRY_OF_ORIGIN', 'QUANTITY_KIND', 'HAS_MRP_CANDIDATE', 'HAS_NET_QUANTITY_CANDIDATE', 'HAS_MANUFACTURER_CANDIDATE', 'HAS_PACKER_CANDIDATE', 'HAS_IMPORTER_CANDIDATE', 'HAS_CONSUMER_CARE_CANDIDATE', 'HAS_MONTH_YEAR_CANDIDATE', 'HAS_COMMON_NAME_CANDIDATE', 'HAS_COUNTRY_OF_ORIGIN_CANDIDATE', 'OCR_EVIDENCE_AVAILABLE', 'OCR_CONFIDENCE_STATE', 'DECLARATION_CONFLICT_PRESENT', name='context_fact_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('source_type', sa.Enum('INSPECTOR_INPUT', 'INSPECTION_METADATA', 'DECLARATION_CANDIDATE', 'OCR_EVIDENCE', 'SYSTEM_INFERENCE', 'MANUAL_OVERRIDE', name='context_source_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_reference_id', sa.String(length=36), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('resolution_state', sa.Enum('KNOWN', 'INFERRED', 'UNKNOWN', 'CONFLICTING', 'REVIEW_REQUIRED', name='fact_resolution_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('explanation', sa.String(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['context_resolution_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_facts_inspection_id'), 'context_facts', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_context_facts_run_id'), 'context_facts', ['run_id'], unique=False)
    op.create_table('inspection_contexts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('context_version', sa.String(length=32), nullable=False),
    sa.Column('resolved', sa.JSON(), nullable=False),
    sa.Column('resolution_status', sa.Enum('KNOWN', 'INFERRED', 'UNKNOWN', 'CONFLICTING', 'REVIEW_REQUIRED', name='context_resolution_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('conflicts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['context_resolution_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index(op.f('ix_inspection_contexts_inspection_id'), 'inspection_contexts', ['inspection_id'], unique=False)
    op.create_table('rule_input_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['context_resolution_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index(op.f('ix_rule_input_snapshots_inspection_id'), 'rule_input_snapshots', ['inspection_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_input_snapshots_inspection_id'), table_name='rule_input_snapshots')
    op.drop_table('rule_input_snapshots')
    op.drop_index(op.f('ix_inspection_contexts_inspection_id'), table_name='inspection_contexts')
    op.drop_table('inspection_contexts')
    op.drop_index(op.f('ix_context_facts_run_id'), table_name='context_facts')
    op.drop_index(op.f('ix_context_facts_inspection_id'), table_name='context_facts')
    op.drop_table('context_facts')
    op.drop_index(op.f('ix_context_resolution_runs_inspection_id'), table_name='context_resolution_runs')
    op.drop_table('context_resolution_runs')
    # ### end Alembic commands ###
