"""Phase 8 versioned rule evaluation and evidence links."""
from alembic import op
import sqlalchemy as sa
revision = "0007_rules"
down_revision = "0006_context"
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_evaluation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('rule_input_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_sha256', sa.String(length=64), nullable=False),
    sa.Column('ruleset_id', sa.String(length=64), nullable=False),
    sa.Column('ruleset_version', sa.String(length=32), nullable=False),
    sa.Column('ruleset_sha256', sa.String(length=64), nullable=False),
    sa.Column('ruleset_definition', sa.JSON(), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('evaluation_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('evaluation_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='rule_run_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('overall', sa.Enum('PASS', 'FAIL', 'UNCERTAIN', name='rule_overall', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_rules', sa.Integer(), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('uncertain_count', sa.Integer(), nullable=False),
    sa.Column('not_applicable_count', sa.Integer(), nullable=False),
    sa.Column('skipped_rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_input_snapshot_id'], ['rule_input_snapshots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id', 'evaluation_fingerprint', name='uq_rule_evaluation_input')
    )
    op.create_index(op.f('ix_rule_evaluation_runs_inspection_id'), 'rule_evaluation_runs', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_rule_evaluation_runs_rule_input_snapshot_id'), 'rule_evaluation_runs', ['rule_input_snapshot_id'], unique=False)
    op.create_table('rule_evaluation_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evaluation_run_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('rule_version', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('verdict', sa.Enum('PASS', 'FAIL', 'UNCERTAIN', 'NOT_APPLICABLE', name='rule_verdict', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='rule_severity', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('explanation', sa.String(length=2000), nullable=False),
    sa.Column('legal_reference', sa.String(length=500), nullable=False),
    sa.Column('legal_status', sa.Enum('VERIFIED_RULE', 'PROTOTYPE_RULE', 'LEGAL_VERIFICATION_REQUIRED', 'DISABLED', name='rule_legal_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('applicability_state', sa.Enum('APPLICABLE', 'NOT_APPLICABLE', 'UNKNOWN', name='rule_applicability_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('evidence_confidence', sa.Float(), nullable=True),
    sa.Column('rule_definition', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['rule_evaluation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_evaluation_results_evaluation_run_id'), 'rule_evaluation_results', ['evaluation_run_id'], unique=False)
    op.create_table('rule_evaluation_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_type', sa.Enum('DECLARATION', 'OCR_BLOCK', 'IMAGE', 'CONTEXT_FACT', 'COVERAGE', name='rule_evidence_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('declaration_candidate_id', sa.String(length=36), nullable=True),
    sa.Column('ocr_block_id', sa.String(length=36), nullable=True),
    sa.Column('inspection_image_id', sa.String(length=36), nullable=True),
    sa.Column('context_fact_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_role', sa.Enum('SUPPORTING', 'CONTRADICTING', 'MISSING_EXPECTED', 'CONTEXT', name='rule_evidence_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['rule_evaluation_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_evaluation_evidence_result_id'), 'rule_evaluation_evidence', ['result_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_evaluation_evidence_result_id'), table_name='rule_evaluation_evidence')
    op.drop_table('rule_evaluation_evidence')
    op.drop_index(op.f('ix_rule_evaluation_results_evaluation_run_id'), table_name='rule_evaluation_results')
    op.drop_table('rule_evaluation_results')
    op.drop_index(op.f('ix_rule_evaluation_runs_rule_input_snapshot_id'), table_name='rule_evaluation_runs')
    op.drop_index(op.f('ix_rule_evaluation_runs_inspection_id'), table_name='rule_evaluation_runs')
    op.drop_table('rule_evaluation_runs')
    # ### end Alembic commands ###
